export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FILTER_ARTICLES = "FILTER_ARTICLES";
export const CLEAN_ARTICLES = "CLEAN_ARTICLES";

export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const UPDATE_ARTICLE_SUCCESS = "  UPDATE_ARTICLE_SUCCESS";
export const CLEAN_ARTICLE = "CLEAN_ARTICLE";

export const FETCH_VIDEOS = "FETCH_VIDEOS";
export const FETCH_RANDOM_VIDEOS = "FETCH_RANDOM_VIDEOS";
export const FILTER_VIDEOS = "FILTER_VIDEOS";
export const CLEAN_VIDEOS = "CLEAN_VIDEOS";

export const FETCH_VIDEO = "FETCH_VIDEO";
export const CREATE_VIDEO = "CREATE_VIDEO";
export const UPDATE_VIDEO_SUCCESS = "  UPDATE_VIDEO_SUCCESS";
export const CLEAN_VIDEO = "CLEAN_VIDEO";

export const FETCH_LOGGED_IN_USER = "FETCH_LOGGED_IN_USER";
export const LOGOUT = "LOGOUT";
