export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FILTER_ARTICLES = "FILTER_ARTICLES";
export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const CLEAN_ARTICLE = "CLEAN_ARTICLE";
export const CLEAN_ARTICLES = "CLEAN_ARTICLES";
