image: node:alpine

variables:
  PUBLIC_URL: "/escohotado"

cache:
  paths:
  - escohotado-client/node_modules

stages:
- deploy

pages:
  stage: deploy
  script:
    - cd escohotado-client/
    - yarn
    - yarn  install --force node-sass
    - yarn build --prod
    - mv build ../public
    - cp ../public/index.html ../public/404.html
  artifacts:
    paths:
    - public
  only:
    - master