image: node:8.11.1

variables:
  PUBLIC_URL: "/escohotado"

    
pages:
stages:
- deploy

pages:
  cache:
    paths:
      - ./node_modules/

  stage: deploy
  script:
    - cd escohotado-client/
    - npm install
    - npm run build
    - rm public -rf
    - mv build public
    - cp ../public/index.html ../public/404.html
  artifacts:
    paths:
    - public
  only:
    - dev